const express = require("express");
const sitemapRouter = express.Router();
const logger = require("../helpers/logger");
const {
  countIndexableProfiles,
  getIndexableProfiles,
  getNewestRoastAt,
} = require("../database/sitemap");

// The roast half of the sitemap. The static pages are generated by the frontend
// server, which already owns the route table — see frontEnd/server.js.
//
// Mounted ahead of the JWT middleware in index.js for the same reason the og
// routes are: the callers are crawlers, and a 401 means the sitemap is simply
// never read.

const SITE = (process.env.SITE_ORIGIN || "https://instaroasts.com").replace(/\/$/, "");

// The spec caps a sitemap at 50,000 URLs / 50MB uncompressed. 45,000 leaves
// room to grow into without a shard ever having to be re-cut.
const SHARD_SIZE = Number(process.env.SITEMAP_SHARD_SIZE) || 45000;

// Both queries are full aggregates over every roast ever generated. Crawlers
// re-fetch a sitemap far more often than the answer changes, so the result is
// held in memory rather than recomputed per hit.
const CACHE_TTL_MS = Number(process.env.SITEMAP_CACHE_TTL_MS) || 6 * 60 * 60 * 1000;
const cache = new Map();

async function cached(key, produce) {
  const hit = cache.get(key);
  if (hit && hit.expires > Date.now()) return hit.value;

  const value = await produce();
  cache.set(key, { value, expires: Date.now() + CACHE_TTL_MS });
  return value;
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// W3C date, which is what <lastmod> takes.
function isoDate(value) {
  const d = value instanceof Date ? value : new Date(value);
  return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
}

// Priority is a relative hint within our own sitemap, not a ranking lever — it
// tells the crawler which of our pages to reach first. Reach is the honest
// proxy for that: a page about an account millions of people search for is
// worth crawling before one about an account with ten thousand.
function priorityFor(followers) {
  const n = Number(followers) || 0;
  if (n >= 1_000_000) return "0.9";
  if (n >= 100_000) return "0.8";
  if (n >= 10_000) return "0.7";
  return "0.6";
}

function renderUrlset(entries) {
  const body = entries
    .map(
      (e) => `  <url>
    <loc>${escapeXml(e.loc)}</loc>${e.lastmod ? `
    <lastmod>${e.lastmod}</lastmod>` : ""}
    <changefreq>${e.changefreq}</changefreq>
    <priority>${e.priority}</priority>
  </url>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;
}

/**
 * How many roast shards exist and when they last changed.
 *
 * The frontend calls this to build the sitemap index, so the shard count is
 * derived from the live row count rather than configured in two places.
 */
sitemapRouter.get("/sitemap/manifest", async (req, res) => {
  try {
    const { count, lastmod } = await cached("manifest", async () => {
      const [count, newest] = await Promise.all([
        countIndexableProfiles(),
        getNewestRoastAt(),
      ]);
      return { count, lastmod: isoDate(newest) };
    });

    res.set("Cache-Control", "public, max-age=21600");
    return res.json({
      count,
      lastmod,
      shardSize: SHARD_SIZE,
      // Always at least one shard: an empty <sitemapindex> is invalid, and an
      // empty urlset is not.
      shards: Math.max(1, Math.ceil(count / SHARD_SIZE)),
    });
  } catch (err) {
    logger.error("[sitemap] manifest failed", { error: err.message });
    return res.status(500).json({ error: "failed" });
  }
});

sitemapRouter.get("/sitemap/roasts/:shard.xml", async (req, res) => {
  const shard = Number(req.params.shard);
  if (!Number.isInteger(shard) || shard < 1 || shard > 1000) {
    return res.status(404).type("txt").send("Not found");
  }

  try {
    const xml = await cached(`roasts:${shard}`, async () => {
      const rows = await getIndexableProfiles(SHARD_SIZE, (shard - 1) * SHARD_SIZE);
      return renderUrlset(
        rows.map((row) => ({
          loc: `${SITE}/${encodeURIComponent(row.username)}`,
          lastmod: isoDate(row.lastmod),
          // A roast is generated once and cached; the page text does not drift.
          changefreq: "monthly",
          priority: priorityFor(row.follower),
        }))
      );
    });

    res.set("Cache-Control", "public, max-age=21600");
    return res.type("application/xml").send(xml);
  } catch (err) {
    logger.error("[sitemap] shard render failed", { shard, error: err.message });
    return res.status(500).type("txt").send("Failed");
  }
});

module.exports = sitemapRouter;
