import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export function Faq() {
  return (
    <div className="m-5 p-5">
      <span
        style={{ fontFamily: "Sansita" }}
        className="flex text-3xl lg:text-5xl p-4 lg:p-5  justify-center"
      >
        FAQs
      </span>
      <Accordion type="single" collapsible>
        <AccordionItem value="item-1">
          <AccordionTrigger>Can I Roast anyone?</AccordionTrigger>
          <AccordionContent>
            Yes!. You can roast & analyse anyone as long as the data is
            publicily avaialable on the internet.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
      <Accordion type="single" collapsible>
        <AccordionItem value="item-1">
          <AccordionTrigger>Is this free?</AccordionTrigger>
          <AccordionContent>Yes! It's free !!</AccordionContent>
        </AccordionItem>
      </Accordion>
      <Accordion type="single" collapsible>
        <AccordionItem value="item-1">
          <AccordionTrigger>How long does it take?</AccordionTrigger>
          <AccordionContent>
            It depends on the amount of data we need to process, but most of the
            times it takes around 1 to 2 minutes to get your roast card ready to
            go! if it takes longer than 2 minutes, please contact us!
          </AccordionContent>
        </AccordionItem>
      </Accordion>
      <Accordion type="single" collapsible>
        <AccordionItem value="item-1">
          <AccordionTrigger>How long you store my data?</AccordionTrigger>
          <AccordionContent>
            We don't store any data besides the data generated by the AI itself,
            we store/cache your profile information for 90 days.At any time,
            please contact us if you want us to delete your data.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
      <Accordion type="single" collapsible>
        <AccordionItem value="item-1">
          <AccordionTrigger>
            Can I roast a profile multiple times?
          </AccordionTrigger>
          <AccordionContent>
            Yes, profiles can be roasted multiple times,each re-scan has the
            same fee as the first full analysis. We keep track of previous roast
            and "version" them for you, so you can roll multiple iterations.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </div>
  );
}
