name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          cp ./backEnd/.env.example ./backEnd/.env
          echo "X_RAPIDAPI_KEY=${{ secrets.X_RAPIDAPI_KEY }}" >> ./backEnd/.env
          echo "X_RAPIDAPI_HOST=${{ secrets.X_RAPIDAPI_HOST }}" >> ./backEnd/.env
          echo "URL=${{ secrets.URL }}" >> ./backEnd/.env
          echo "DB=${{ secrets.DB }}" >> ./backEnd/.env
          echo "APIKEY=${{ secrets.APIKEY }}" >> ./backEnd/.env
          echo "MODEL_NAME=${{ secrets.MODEL_NAME }}" >> ./backEnd/.env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> ./backEnd/.env
          docker build -t instagram-roast-backend:latest ./backEnd
          
      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          project_id: roast-123
          export_default_credentials: true
      
      - name: Configure Docker Client
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Push the Docker image
        env: 
          ARTIFACT_REGISTRY_URL: asia-south1-docker.pkg.dev/roast-123/instagram-roast-backend
        run: |
          docker tag instagram-roast-backend:latest $ARTIFACT_REGISTRY_URL/instagram-roast-backend:latest
          docker push $ARTIFACT_REGISTRY_URL/instagram-roast-backend:latest      

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build -t instagram-roast-frontend:latest ./frontEnd \
            --build-arg VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }}
          
      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          project_id: roast-123
          export_default_credentials: true
      
      - name: Configure Docker Client
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Push the Docker image
        env: 
          ARTIFACT_REGISTRY_URL: asia-south1-docker.pkg.dev/roast-123/instagram-roast-frontend
        run: |
          docker tag instagram-roast-frontend:latest $ARTIFACT_REGISTRY_URL/instagram-roast-frontend:latest
          docker push $ARTIFACT_REGISTRY_URL/instagram-roast-frontend:latest


  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          project_id: roast-123
          export_default_credentials: true
          
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service_name: "instagram-roast-backend"
          image: "asia-south1-docker.pkg.dev/roast-123/instagram-roast-backend/instagram-roast-backend:latest"
          platform: "managed"
          region: "asia-south1"
          port: 8080


  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Configure GCP Credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          project_id: roast-123
          export_default_credentials: true
          
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service_name: "instagram-roast-frontend"
          image: "asia-south1-docker.pkg.dev/roast-123/instagram-roast-frontend/instagram-roast-frontend:latest"
          platform: "managed"
          region: "asia-south1"
          port: 5173
